version: '3.8'

services:
  frontend:
    build:
      context: ./client/doctor-ai
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./client/doctor-ai/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./doctor_ai
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./doctor_ai/pdfs:/app/pdfs
    env_file:
      - ./doctor_ai/.env
